# Generated by Django 4.2.2 on 2023-06-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('cooking', 'Cooking'), ('technology', 'Technology'), ('life style', 'Life style'), ('car', 'Car')], default='life style', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
