# Generated by Django 4.2.2 on 2023-06-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
