# Generated by Django 4.2.2 on 2023-06-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0005_rename_content_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
